### PR TITLE
fix wait logic

### PR DESCRIPTION
**Pull request by ethanhua**
the countdown create logic not match that task complete and reduce count logic

### CODE REVIEW

**Comment by ethanhua** [comment]
thanks for your project, i found the problem when i apply it to my app,  I fixed it and you can check it and if it works you can merge it in

**Comment by idisfkj** [comment]
I think this logic is not a problem, because if it `callCreateOnMainThread() == true`, that the component is initialized in the main thread, and the main thread is blocked by default, so there's no need to call `mNeedAwaitCount.IncrementAndGet()` wait for additional jam.

However, the `await()` method is somewhat problematic, and I guess the problem you are experiencing is caused by the following reasons.

The cause should be this code in `StartupManagerDispatcher`:
```
    override fun notifyChildren(dependencyParent: Startup<*>, result: Any?, sortStore: StartupSortStore) {
        // immediately notify main thread,Unblock the main thread.
        if (dependencyParent.waitOnMainThread()) {
            needAwaitCount.incrementAndGet()
            awaitCountDownLatch?.countDown()
        }
        ...
    }
```
It should be amended to:
```
    override fun notifyChildren(dependencyParent: Startup<*>, result: Any?, sortStore: StartupSortStore) {
        // immediately notify main thread,Unblock the main thread.
        if (dependencyParent.waitOnMainThread() && !dependencyParent.callCreateOnMainThread()) {
            needAwaitCount.decrementAndGet()
            awaitCountDownLatch?.countDown()
        }
        ...
    }
```
Will this solve your problems?

**Comment by ethanhua** [comment]
I also tried to do this at first, but one thing to consider is that instead of saying that calls on the Main thread are blocked, it's possible that this task depends on the completion of an asynchronous task, and if we don't block artificially at this point, we have a problem

**Comment by idisfkj** [comment]
Thank you for your pr.

**Pull request merged**
